# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
          # Label used to access the service container
          redis:
            # Docker Hub image
            image: redis
            #
            ports:
              # Opens tcp port 6379 on the host and service container
              - 6379:6379
          zookeeper:
            image: zookeeper
            ports:
              - 2181:2181
            
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Config with Maven
      run: mvn -B package --file config/pom.xml
    - name: Build Consumer with Maven
      run: mvn -B package --file consumer/pom.xml
    - name: Build Producer with Maven
      run: mvn -B package --file producer/pom.xml
    - name: Build Worker with Maven
      run: mvn -B package --file worker/pom.xml
